# Travis CI configuration for libseccomp

# https://docs.travis-ci.com/user/trusty-ci-environment
# https://wiki.ubuntu.com/Releases

dist: trusty
sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

language: c
compiler: gcc

addons:
  apt:
    packages:
      - build-essential
      - python
      - python-dev
      - python-pip
      - valgrind

# NOTE: sudo is required for python/cython to work correctly

# resolve any remaining dependency issues
before_install:
  # ubuntu 14.04 (trusty) has an old version of cython
  - sudo pip install cython

# perform the build and fail immediately on error
install:
  - sudo ./autogen.sh
  - sudo ./configure --enable-python
  - sudo make check-build

# run all of the tests independently, fail if any of the tests error
script:
  - (cd src; sudo make check)
  - (cd tests; sudo make check)
  - (cd tests; sudo ./regression -T live)
